### ISSUE TITLE
Add Google auth environment variable to Heroku

### ISSUE THREAD

**Issue by SimonLab** [dwyl/app-mvp-phoenix#45]
The current environment variables define on Heroku:
![image](https://user-images.githubusercontent.com/6057298/70637850-d6bd6b00-1c2f-11ea-88c7-f6a18af35795.png)

- [ ] Add `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`

@nelsonic do you have a dedicated google application already created?

**Comment by nelsonic** [comment]
https://dashboard.heroku.com/apps/dwylapp/settings
![dwylapp-google-env-vars](https://user-images.githubusercontent.com/194400/70639365-4af90e00-1c32-11ea-9f88-2734491e51d9.png)

Done. ✅

**Comment by nelsonic** [comment]
Note: these keys are _only_ valid for  dwylapp.herokuapp.com 
I don't know what that means for Review Apps ... 💭

**Comment by SimonLab** [comment]
Yes we will need to add them (or different ones) for the review apps also.

Still an error while deploying, from the look of the error I think it's still an environment variable error:
![image](https://user-images.githubusercontent.com/6057298/70640743-56e5cf80-1c34-11ea-8849-bdea8fdeebc7.png)

**Comment by nelsonic** [comment]
Build failed -- check your build output: https://dashboard.heroku.com/apps/abe5b24b-1755-4954-910c-a60e99d9f75f/activity/builds/9957bf21-b090-40a9-81b2-b8414bc7c29d

![image](https://user-images.githubusercontent.com/194400/70640484-e8a10d00-1c33-11ea-8cd7-ed906eecbab4.png)

Dang ... I was seeing this error the other day on `localhost` ... https://github.com/dwyl/learn-elixir/issues/147
Sadly I wasn't able to figure out how to resolve it. as you can see, the stack trace is _useless_! 😞 
Attempting to _manually_ deploy the `master` branch fails with the same error ...

**Comment by nelsonic** [comment]
@SimonLab Yeah, I think it's the `ENCRYPTION_KEYS` ... 🤔

**Comment by SimonLab** [comment]
Yes just confirmed on localhost, it's missing the ENCRYPTION_KEYS. I think at this stage we can add only one key and later one add another one if necessary

**Comment by nelsonic** [comment]
https://github.com/dwyl/fields#2-ensure-you-have-the-necessary-environment-variables-
`|>` https://github.com/dwyl/phoenix-ecto-encryption-example#how-to-generate-aes-encryption-keys

```
iex
:crypto.strong_rand_bytes(32) |> :base64.encode
```
Paste resulting string into Heroku Config Vars. ✅ 
Re-deploying ... ⏳

**Comment by nelsonic** [comment]
the slowest thing in the Heroku Build is installing node.js dependencies ... 🙄 ⏳

**Comment by SimonLab** [comment]
deployed:
![image](https://user-images.githubusercontent.com/6057298/70641522-ad9fd900-1c35-11ea-9238-b6ebba1b6af6.png)

**Comment by SimonLab** [comment]
also: `This application is still using the Cedar-14 stack for which the end-of-life window began May 1, 2019:`

**Comment by nelsonic** [comment]
Before:
![image](https://user-images.githubusercontent.com/194400/70641756-01aabd80-1c36-11ea-8742-04b4e4a982f6.png)

After:
![image](https://user-images.githubusercontent.com/194400/70641765-07a09e80-1c36-11ea-867c-1effae44cf78.png)

**Comment by nelsonic** [comment]
I consider this task `#done` ✅
